### ISSUE TITLE
Direct link to a talent tree not working

### ISSUE THREAD

**Issue by Mercer100** [ginpachi987/wow-df-talent-calculator#1]
Hi,

first of all thank you for your great tool. 

I try to implement your talent tree in a website. It's working fine besides one bigger issue.

If you want to open the url of a talent tree where you've already set the skill points you will get a 404 error. On your site it's working as expected.

**Example:** 

If you open [https://projects.yoro.dev/df-talents/druid/7hox-1ekg/balance/](https://projects.yoro.dev/df-talents/druid/7hox-1ekg/balance/) on your site it's working fine, but not on others,

Could you give a tip, how did you managed the right loading of the url including the query string?

**Comment by ginpachi987** [comment]
Hi, thanks for the kind words.

In order for this to work you need to redirect all "subpage" requests to index.html in the calculator's base directory. I'm doing this by configuring .htaccess file.

It should look something like this
```
RewriteCond %{REQUEST_URI} !(.html|.js|.css)
RewriteCond %{REQUEST_URI} !^(.*).(jpg|jpeg|png|gif|txt|ico)
RewriteCond %{REQUEST_URI} !(.eot|.ttf|.woff)
RewriteRule ^(.*) ./index.html [NC,L]
```

But this method may not apply to your hosting provider.

**Comment by Mercer100** [comment]
Thank you! Works perfectly.
