### ISSUE TITLE
Error in professions tab

### ISSUE THREAD

**Issue by Mercer100** [ginpachi987/wow-df-talent-calculator#10]
Hello,

there seems to be an error in the "professions" tab. If you open the skill tree of a profession I get the following error in the console and the skill tree isn't working.

![error](https://user-images.githubusercontent.com/90628241/207419051-26ef3d90-5cc0-4f18-a53a-ed2a779e274c.jpg)

Do you have an idea how to solve it?

Thanks.

**Comment by ginpachi987** [comment]
Outdated
