### ISSUE TITLE
Compatibility with wowdb icon

### ISSUE THREAD

**Issue by tytannial** [ginpachi987/wow-df-talent-calculator#3]
wowhead close their service in some place. I want use `https://icons.wowdb.com/beta/large/` as icon site.
![image](https://user-images.githubusercontent.com/11215623/181139820-756a2374-92ac-4e50-b5b8-fa459edbfaa5.png)
The problem is an extra '/', icon url of wowdb does not support that slash.

Invaild: `https://icons.wowdb.com/beta/large//xxxxxx.jpg`
correct: `https://icons.wowdb.com/beta/large/xxxxxx.jpg`

**Comment by ginpachi987** [comment]
Hi, yes I've been already told wowhead isn't available at least in China. Thanks for the link I'm gonna change it globally in the newest version later today.

**Comment by ginpachi987** [comment]
Fixed
