### ISSUE TITLE
Warrior talent two-handed should be one-handed

### ISSUE THREAD

**Issue by victorp13** [ginpachi987/wow-df-talent-calculator#9]
This talent down the Warrior tree is shown as two-handed:
![image](https://user-images.githubusercontent.com/1854749/198849609-2871bda7-2cd6-4902-a177-581ee689c59f.png)

This should be one-handed:
![image](https://user-images.githubusercontent.com/1854749/198849586-73e6a47e-366d-4b05-ac5d-b809cd7ee6a9.png)

I'd make a Pull Request to suggest a fix but this is coming from the /api on your website of which I have no source :)

**Comment by ginpachi987** [comment]
So, this is due to the fact this talent has different description for different specs. I didn't manage to code this behavior yet.

**Comment by victorp13** [comment]
Ah; interesting! I didn't know this was in the game at all (different class talents per spec).

**Comment by ginpachi987** [comment]
Implemented
